// THIS SEED SCRIPT WAS GENERATED BY CLAUDE !!!

import dotenv from "dotenv";
dotenv.config({ path: "./../.env" });
import mongoose from "mongoose";
import Item from "./../models/item.js";
import Business from "./../models/business.js";
import Stock from "./../models/stock.js";

import { setServers } from "dns";
setServers(["8.8.8.8", "8.8.4.4"]);

const MONGO_URI = process.env.MONGO_URL;

console.log(process.env.GEOAPIUFY_API_KEY);

const businesses = [
  {
    name: "Save On Foods",
    username: "saveonfoods_main",
    password: "password123",
    email: "contact@saveonfoods.ca",
    address: "1766 W 3rd Ave, Vancouver, BC V6J 1K1",
    open: 7,
    close: 22,
  },
  {
    name: "No Frills",
    username: "nofrills_commercial",
    password: "password123",
    email: "contact@nofrills.ca",
    address: "3575 Commercial St, Vancouver, BC V5N 4E8",
    open: 8,
    close: 21,
  },
  {
    name: "TNT Kingsway",
    username: "tnt_kingsway",
    password: "password123",
    email: "contact@tnt.ca",
    address: "179 Keefer Pl, Vancouver, BC V6B 6L4",
    open: 9,
    close: 21,
  },
  {
    name: "Persia Foods",
    username: "persia_foods",
    password: "password123",
    email: "contact@persiafoods.ca",
    address: "1110 Mainland St, Vancouver, BC V6B 5P1",
    open: 9,
    close: 20,
  },
  {
    name: "Famous Foods",
    username: "famous_foods",
    password: "password123",
    email: "contact@famousfoods.ca",
    address: "1595 Kingsway, Vancouver, BC V5N 2R8",
    open: 9,
    close: 18,
  },
];

// group code -> realistic items with full retail prices
const itemsByGroup = {
  fp: [
    { name: "bananas (bunch)", price: 1.99 },
    { name: "organic apples (3lb)", price: 5.49 },
    { name: "strawberries (1lb)", price: 4.99 },
    { name: "avocados (3 pack)", price: 5.99 },
    { name: "baby spinach (5oz)", price: 3.99 },
    { name: "romaine lettuce", price: 2.49 },
    { name: "cherry tomatoes (pint)", price: 3.99 },
    { name: "blueberries (6oz)", price: 4.49 },
    { name: "broccoli crown", price: 2.99 },
    { name: "sweet potatoes (2lb)", price: 3.49 },
    { name: "green grapes (2lb)", price: 6.99 },
    { name: "mini cucumbers (6 pack)", price: 3.49 },
    { name: "red bell peppers (2 pack)", price: 4.49 },
    { name: "mangoes (each)", price: 2.49 },
    { name: "fresh basil (bunch)", price: 2.99 },
    { name: "kale (bunch)", price: 2.99 },
    { name: "lemons (bag of 6)", price: 3.99 },
    { name: "mushrooms (8oz)", price: 3.49 },
    { name: "carrots (2lb bag)", price: 2.99 },
    { name: "zucchini (each)", price: 1.49 },
  ],
  ms: [
    { name: "chicken breast (1kg)", price: 14.99 },
    { name: "ground beef (500g)", price: 7.99 },
    { name: "atlantic salmon fillet (300g)", price: 11.99 },
    { name: "pork tenderloin (500g)", price: 9.49 },
    { name: "jumbo shrimp (400g)", price: 12.99 },
    { name: "chicken thighs (1kg)", price: 10.99 },
    { name: "beef stewing cubes (500g)", price: 8.99 },
    { name: "tilapia fillets (400g)", price: 8.49 },
    { name: "lamb chops (4 pack)", price: 16.99 },
    { name: "smoked salmon (200g)", price: 9.99 },
    { name: "italian sausages (4 pack)", price: 7.49 },
    { name: "turkey breast slices (300g)", price: 6.99 },
    { name: "cod fillets (400g)", price: 10.49 },
    { name: "bacon (375g)", price: 6.99 },
    { name: "mussels (2lb bag)", price: 7.99 },
    { name: "chicken wings (1kg)", price: 9.49 },
    { name: "ground pork (500g)", price: 6.49 },
    { name: "beef sirloin steak (300g)", price: 13.99 },
    { name: "crab cakes (4 pack)", price: 11.49 },
    { name: "prosciutto (100g)", price: 7.49 },
  ],
  de: [
    { name: "whole milk (2l)", price: 5.49 },
    { name: "large eggs (dozen)", price: 5.99 },
    { name: "old cheddar (300g)", price: 7.49 },
    { name: "greek yogurt (750g)", price: 5.99 },
    { name: "butter (454g)", price: 5.99 },
    { name: "cream cheese (250g)", price: 4.49 },
    { name: "mozzarella (340g)", price: 6.49 },
    { name: "sour cream (500ml)", price: 3.49 },
    { name: "free range eggs (dozen)", price: 7.99 },
    { name: "brie wheel (200g)", price: 6.99 },
    { name: "oat milk (1.75l)", price: 4.99 },
    { name: "whipping cream (500ml)", price: 4.49 },
    { name: "goat cheese (150g)", price: 5.99 },
    { name: "cottage cheese (500g)", price: 4.49 },
    { name: "parmesan wedge (200g)", price: 8.99 },
    { name: "yogurt tubes (12 pack)", price: 5.49 },
    { name: "chocolate milk (1l)", price: 3.49 },
    { name: "havarti slices (200g)", price: 5.49 },
    { name: "egg whites (500ml)", price: 4.99 },
    { name: "ricotta (475g)", price: 5.49 },
  ],
  bk: [
    { name: "sourdough loaf", price: 5.49 },
    { name: "croissants (4 pack)", price: 5.99 },
    { name: "whole wheat bread", price: 3.99 },
    { name: "bagels (6 pack)", price: 4.49 },
    { name: "cinnamon raisin bread", price: 4.99 },
    { name: "dinner rolls (12 pack)", price: 4.49 },
    { name: "baguette", price: 2.99 },
    { name: "chocolate muffins (4 pack)", price: 5.49 },
    { name: "naan bread (4 pack)", price: 3.99 },
    { name: "banana bread loaf", price: 6.49 },
    { name: "pita bread (6 pack)", price: 3.49 },
    { name: "butter tarts (6 pack)", price: 5.99 },
    { name: "focaccia bread", price: 4.99 },
    { name: "scones (4 pack)", price: 5.49 },
    { name: "rye bread loaf", price: 4.49 },
    { name: "danish pastries (4 pack)", price: 5.99 },
    { name: "tortillas (10 pack)", price: 3.99 },
    { name: "english muffins (6 pack)", price: 4.49 },
    { name: "brioche buns (4 pack)", price: 4.99 },
    { name: "apple pie", price: 8.99 },
  ],
  ss: [
    { name: "dark chocolate bar (100g)", price: 3.99 },
    { name: "trail mix (350g)", price: 6.49 },
    { name: "gummy bears (200g)", price: 3.49 },
    { name: "potato chips (200g)", price: 4.49 },
    { name: "salted cashews (300g)", price: 8.99 },
    { name: "cookies (350g)", price: 4.99 },
    { name: "rice crackers (150g)", price: 3.99 },
    { name: "dried mangoes (200g)", price: 5.49 },
    { name: "pretzels (300g)", price: 3.99 },
    { name: "granola bars (6 pack)", price: 4.49 },
    { name: "popcorn (3 pack)", price: 4.99 },
    { name: "licorice (200g)", price: 3.49 },
    { name: "mixed nuts (400g)", price: 9.49 },
    { name: "candy assortment (300g)", price: 4.99 },
    { name: "peanut butter cups (4 pack)", price: 3.99 },
    { name: "veggie straws (200g)", price: 4.49 },
    { name: "chocolate almonds (250g)", price: 6.49 },
    { name: "fruit snacks (10 pack)", price: 4.99 },
    { name: "cheese crackers (200g)", price: 3.99 },
    { name: "energy bites (8 pack)", price: 5.99 },
  ],
};

function randomBetween(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomDiscount(fullPrice) {
  // 30%-80% off -> ref_price is 20%-70% of full price
  const discountPct = 0.3 + Math.random() * 0.5;
  return parseFloat((fullPrice * (1 - discountPct)).toFixed(2));
}

function randomExpiry() {
  const hours = randomBetween(24, 72);
  return new Date(Date.now() + hours * 3600000);
}

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  // Clear existing data
  await Item.deleteMany({});
  await Business.deleteMany({});
  await Stock.deleteMany({});
  console.log("Cleared existing data");

  // Create businesses
  const savedBusinesses = [];
  for (const biz of businesses) {
    const doc = await Business.create(biz);
    savedBusinesses.push(doc);
    console.log(`Created business: ${doc.username}`);
  }

  // Flatten all items into a pool
  const allItems = Object.entries(itemsByGroup).flatMap(([group, items]) =>
    items.map((item) => ({ ...item, group })),
  );

  // Distribute 100 items across 5 businesses (20 each)
  const shuffled = allItems.sort(() => Math.random() - 0.5);

  for (let i = 0; i < savedBusinesses.length; i++) {
    const biz = savedBusinesses[i];
    const bizItems = shuffled.slice(i * 20, (i + 1) * 20);

    const itemDocs = bizItems.map((item) => ({
      name: item.name,
      price: item.price,
      ref_price: randomDiscount(item.price),
      quantity: randomBetween(1, 80),
      business: biz._id,
      group: item.group,
      expiry: randomExpiry(),
    }));

    const savedItems = await Item.insertMany(itemDocs);

    // Build stock map: key is item name (or index), value is item ObjectId
    const stockMap = {};
    savedItems.forEach((item, idx) => {
      stockMap[`item_${idx}`] = item._id;
    });

    await Stock.create({
      business: biz._id,
      items: stockMap,
    });

    console.log(`${biz.username}: ${savedItems.length} items stocked`);
  }

  console.log("\nSeed complete: 100 items across 5 businesses");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
